import { createRoot } from 'react-dom/client';
import React, { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, ChevronDown, Moon, Play, Sun, X } from 'lucide-react';
import './styles.css';
import './work-alignment.css';
import './milestone-contact-alignment.css';
import AboutMe from "./components/AboutMe/AboutMe.jsx";

const ASSET_BASE = 'https://raw.githubusercontent.com/yokeshkannan3d/Yokeshkannan/main';
const REEL = `${ASSET_BASE}/public/videos/reel.mp4`;
const PRODUCT_VIZ_VIDEO = 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/Product_vizualization.mp4';
const PRODUCT_VIZ_COVER = 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/cover.png';

const WORK_CATEGORIES = [
  { id: 'vfx', title: 'VFX & Compositing', subtitle: 'Visual effects, compositing & cinematic finishing', image: `${ASSET_BASE}/public/images/work-2.svg`, coverVideo: REEL, works: [{ title: 'Show Reel', video: REEL }]},
  { id: 'product-viz', title: '3D Product Visualization', subtitle: 'Product modeling, materials, lighting & renders', image: PRODUCT_VIZ_COVER, coverVideo: PRODUCT_VIZ_VIDEO, works: [{ title: '3D Product Visualization', video: PRODUCT_VIZ_VIDEO, image: PRODUCT_VIZ_COVER }]},
  { id: 'hard-surface', title: 'Hard Surface Modelling', subtitle: 'Detailed mechanical, vehicle & industrial assets', image: 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/Gun_1.png', subcategories: [
    { id: 'gun-models', title: 'Gun Models', subtitle: 'Desert Eagle — 3D model', image: 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/Gun_1.png', works: [
      { title: 'Gun Model 01', image: 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/Gun_1.png' },
      { title: 'Gun Model 02', image: 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/Gun_2.png' },
      { title: 'Gun Model 03', image: 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/Gun_3.png' }
    ]},
    { id: 'car-models', title: 'Car Models', subtitle: 'Hard-surface vehicle modelling & detailing', image: 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/car.jpg', works: [{ title: 'Car Model', image: 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/car.jpg' }]}
  ], works: []},
  { id: 'motion', title: '3D Animation', subtitle: 'Character animation, walk cycles & motion studies', image: 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/walk%20cycle.gif', works: [
    { title: 'Walk Cycle', image: 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/walk%20cycle.gif' },
    { title: 'TOBY0001', video: 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/animation/TOBY0001.mp4' },
    { title: 'Animation - Product Promo', video: 'https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/animation/Animation%20-%20product%20promo.mp4' }
  ]},
];

function Nav({ theme, onToggleTheme }) { return <header className="nav"><a className="nav-logo" href="#top" aria-label="Yokesh Kannan home">YK</a><nav className="nav-links" aria-label="Primary navigation"><a href="#about">About</a><a href="#work">Work</a><a href="#milestones">Milestones</a><a href="#contact">Contact</a></nav><button className="theme-toggle" onClick={onToggleTheme} aria-label={theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'} title={theme === 'dark' ? 'Light mode' : 'Dark mode'}>{theme === 'dark' ? <Sun size={17} /> : <Moon size={17} />}<span>{theme === 'dark' ? 'LIGHT' : 'DARK'}</span></button></header>; }
function Hero() { const [open,setOpen]=useState(false); useEffect(()=>{if(!open)return;const onKey=e=>e.key==='Escape'&&setOpen(false);document.addEventListener('keydown',onKey);document.body.classList.add('modal-open');return()=>{document.removeEventListener('keydown',onKey);document.body.classList.remove('modal-open');}},[open]); return <>{<section id="top" className="hero"><video className="hero-preview" autoPlay muted loop playsInline preload="metadata"><source src={REEL} type="video/mp4"/></video><div className="hero-shade"/><div className="hero-copy"><div><h1>JUMP INTO MY <span>WORLD</span></h1><button className="reel-cta" onClick={()=>setOpen(true)}><span className="play-ring"><Play size={25} fill="currentColor"/></span><span>PLAY SHOW REEL</span></button></div></div><button className="scroll-cue" onClick={()=>document.querySelector('#about')?.scrollIntoView({behavior:'smooth'})} aria-label="Scroll to About"><ChevronDown size={22}/></button></section>}{open&&<div className="reel-modal" role="dialog" aria-modal="true" aria-label="Show reel" onClick={()=>setOpen(false)}><button className="reel-close" onClick={()=>setOpen(false)} aria-label="Close reel"><X size={30}/></button><div className="reel-player" onClick={e=>e.stopPropagation()}><video autoPlay controls playsInline><source src={REEL} type="video/mp4"/></video></div></div>}</>; }
function About(){return <AboutMe/>;}
function CategoryCard({category,onOpen}){return <button className="work-card work-category-card" onClick={()=>onOpen(category)} aria-label={`Open ${category.title}`}>{category.coverVideo?<video className="category-card-video" autoPlay muted loop playsInline preload="metadata"><source src={category.coverVideo} type="video/mp4"/></video>:<img src={category.image} alt=""/>}<div className="category-card-overlay"><span className="category-index">{category.id==='vfx'?'01':category.id==='product-viz'?'02':category.id==='hard-surface'?'03':'04'}</span><span className="work-label category-label">{category.title}</span><span className="category-subtitle">{category.subtitle}</span></div></button>;}
function CategoryLibrary({category,onClose}){useEffect(()=>{const onKey=e=>e.key==='Escape'&&onClose();document.addEventListener('keydown',onKey);document.body.classList.add('modal-open');return()=>{document.removeEventListener('keydown',onKey);document.body.classList.remove('modal-open');};},[onClose]);const renderWorks=(works,keyPrefix)=><div className="category-work-grid">{works.map((work,index)=><article className="category-work-item" key={`${keyPrefix}-${index}`}>{work.video?<video className="category-work-video" controls playsInline preload="metadata" poster={work.image||undefined}><source src={work.video} type="video/mp4"/></video>:work.image?<img src={work.image} alt={work.title}/>:<div className="category-work-placeholder"><span>{String(index+1).padStart(2,'0')}</span><small>WORKPIECE</small></div>}<div className="category-work-caption"><span>{String(index+1).padStart(2,'0')}</span><strong>{work.title}</strong></div></article>)}</div>;return <div className="library-modal" onClick={onClose} role="dialog" aria-modal="true" aria-label={`${category.title} work library`}><div className="library-panel category-library-panel" onClick={e=>e.stopPropagation()}><button className="library-close" onClick={onClose} aria-label="Close library"><X size={28}/></button><p className="eyebrow">WORK CATEGORY</p><h3>{category.title}</h3><p className="category-library-description">{category.subtitle}</p>{category.subcategories?category.subcategories.map(sub=><section className="work-subcategory" key={sub.id}><div className="work-subcategory-heading"><span>SUB CATEGORY</span><h4>{sub.title}</h4><p>{sub.subtitle}</p></div>{renderWorks(sub.works,sub.id)}</section>):renderWorks(category.works,category.id)}</div></div>;}
function Work(){const[selected,setSelected]=useState(null);const trackRef=useRef(null);const timerRef=useRef(null);const move=distance=>trackRef.current?.scrollBy({left:distance,behavior:'smooth'});const start=()=>{clearInterval(timerRef.current);timerRef.current=setInterval(()=>{const track=trackRef.current;if(!track)return;const max=track.scrollWidth-track.clientWidth;if(track.scrollLeft>=max-8)track.scrollTo({left:0,behavior:'smooth'});else track.scrollBy({left:430,behavior:'smooth'});},2600);};useEffect(()=>{start();return()=>clearInterval(timerRef.current);},[]);return <section id="work" className="work section-shell"><div className="work-inner"><h2>Made by Yokesh</h2><p className="work-intro">Explore my work by category.</p><div className="carousel-shell" onMouseEnter={()=>clearInterval(timerRef.current)} onMouseLeave={start}><button className="carousel-arrow left" onClick={()=>move(-430)} aria-label="Previous category"><ArrowLeft size={23}/></button><div className="work-track" ref={trackRef} onPointerDown={()=>clearInterval(timerRef.current)} onPointerUp={start}>{[...WORK_CATEGORIES,...WORK_CATEGORIES].map((category,i)=><CategoryCard key={`${category.id}-${i}`} category={category} onOpen={setSelected}/>)}</div><button className="carousel-arrow right" onClick={()=>move(430)} aria-label="Next category"><ArrowRight size={23}/></button></div></div>{selected&&<CategoryLibrary category={selected} onClose={()=>setSelected(null)}/>}</section>;}
function Milestones(){return <section id="milestones" className="milestones section-shell"><div className="content-narrow"><h2>Milestones</h2><div className="milestone-panel"><div className="milestone-item"><img className="milestone-logo" src="https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/Kung_Fu_Tea_Official_Logo.png" alt="Kung Fu Tea logo"/><p>Created optimized low-poly assets for the real-time game engine. Built Boba Run, including vehicles, environment props, and modular assets.</p></div><div className="milestone-item"><img className="milestone-logo" src="https://raw.githubusercontent.com/yokeshkannan3d/portfolio-1/main/assets/M-web-1.png" alt="THEMUSEUM project"/><p>Created an immersive projection-mapping capstone project with THEMUSEUM, supporting students in exploring creative and technical approaches to immersive experiences.</p></div></div></div></section>;}
function Contact(){return <section id="contact" className="contact section-shell"><div className="content-narrow"><h2>Get in Touch</h2><div className="contact-links">
  <a href="https://www.linkedin.com/in/yokesh-kannan" target="_blank" rel="noreferrer" aria-label="LinkedIn">
    <svg className="contact-logo" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M5.2 3.5A2.2 2.2 0 1 1 5.2 8a2.2 2.2 0 0 1 0-4.5ZM3.3 9.3h3.8V21H3.3V9.3Zm6.1 0H13v1.6h.1c.5-.9 1.8-2 3.7-2 4 0 4.7 2.6 4.7 6V21h-3.8v-5.4c0-1.3 0-3-1.9-3s-2.2 1.4-2.2 2.9V21H9.4V9.3Z"/></svg>
  </a>
  <a href="https://www.behance.net/yokeshkannan" target="_blank" rel="noreferrer" aria-label="Behance">
    <svg className="contact-logo" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M3 4.5h6.2c3.1 0 5.1 1.1 5.1 4 0 1.6-.8 2.8-2.2 3.4 2 .6 3 2.1 3 4.2 0 3.3-2.8 4.8-5.8 4.8H3V4.5Zm3.6 6.6h2.9c1.3 0 2.2-.6 2.2-1.9 0-1.5-1.1-1.8-2.4-1.8H6.6v3.7Zm0 6.9h3c1.4 0 2.6-.5 2.6-2.1 0-1.7-1-2.3-2.6-2.3h-3V18ZM16.3 6h5.8v1.8h-5.8V6Zm6.4 8.1c-.2-3.3-2-5.6-5.3-5.6-3 0-5.5 2.3-5.5 6.3 0 3.9 2.3 6.2 5.5 6.2 2.5 0 4.3-1.1 5.2-3.7h-2.9c-.2.8-1.3 1.6-2.2 1.6-1.6 0-2.5-.8-2.6-2.7h7.8c.1-.4 0-1.4 0-2.1Zm-7.7-.1c.1-1 .7-2.3 2.3-2.3 1.2 0 2 .7 2.3 2.3H15Z"/></svg>
  </a>
  <a href="mailto:yokeshkannan3d@gmail.com" aria-label="Gmail">
    <svg className="contact-logo" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M3 5.5h18c.6 0 1 .4 1 1v11c0 .6-.4 1-1 1H3c-.6 0-1-.4-1-1v-11c0-.6.4-1 1-1Zm9 7.1 8.1-5.4H3.9l8.1 5.4Zm0 2.4L4 9.7v6.8h16V9.7L12 15Z"/></svg>
  </a>
  <a href="#" aria-label="Instagram">
    <svg className="contact-logo" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M7.2 2h9.6A5.2 5.2 0 0 1 22 7.2v9.6a5.2 5.2 0 0 1-5.2 5.2H7.2A5.2 5.2 0 0 1 2 16.8V7.2A5.2 5.2 0 0 1 7.2 2Zm0 2A3.2 3.2 0 0 0 4 7.2v9.6A3.2 3.2 0 0 0 7.2 20h9.6a3.2 3.2 0 0 0 3.2-3.2V7.2A3.2 3.2 0 0 0 16.8 4H7.2Zm10.1 1.5a1.2 1.2 0 1 1 0 2.4 1.2 1.2 0 0 1 0-2.4ZM12 7a5 5 0 1 1 0 10 5 5 0 0 1 0-10Zm0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z"/></svg>
  </a>
</div></div></section>;}
function App(){const[theme,setTheme]=useState(()=>{try{return localStorage.getItem('portfolio-theme')||'dark';}catch{return'dark';}});useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('portfolio-theme',theme);}catch{}},[theme]);return <div className={`app theme-${theme}`}><Nav theme={theme} onToggleTheme={()=>setTheme(value=>value==='dark'?'light':'dark')}/><Hero/><About/><Work/><Milestones/><Contact/></div>;}
createRoot(document.getElementById('root')).render(<App/>);
